export const removeCategoryButtonText = "Remove Category";
export const removeProductsButtonText = "Remove Products";
export const addCategoryButtonText = "Add Category";
export const addProductsButtonText = "Add Products";
export const addText = "Add"
export const removeText = "Remove"
export const productsText = "Products"
export const categoryText = "Category"
export const availableProductsText = "Available Products"
